name: otherworkflow2

on:
  pull_request:

permissions:
  contents: read

jobs:
  createartefacts:
    name: create artefacts
    runs-on: ubuntu-latest
    steps:
      - name: do something
        run: |
          mkdir out
          mkdir out/artefactdir
          echo 'MYENV_VAR=value\nBASH_ENV="$(id)"' > out/artefactdir/env

      - name: Upload persist key
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: myartefact
          path: ./out/
